package com.project.huaweiproject;
// Generated 07.Mar.2019 19:37:43 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tasks generated by hbm2java
 */
public class Tasks  implements java.io.Serializable {


     private int logicalref;
     private String task;
     private Date begdate;
     private Date enddate;
     private Date dateline;
     private Date createdate;
     private Integer userref;
     private Date modifieddate;
     private int state;
     private int injecttaskref;
    public Tasks() {
    }

	
    public Tasks(int logicalref) {
        this.logicalref = logicalref;
    }
    public Tasks(int logicalref, String task, Date begdate, Date enddate, Date dateline, Date createdate, Integer userref, Date modifieddate,int state,int injecttaskref) {
       this.logicalref = logicalref;
       this.task = task;
       this.begdate = begdate;
       this.enddate = enddate;
       this.dateline = dateline;
       this.createdate = createdate;
       this.userref = userref;
       this.modifieddate = modifieddate;
       this.state = state;
       this.injecttaskref = injecttaskref;
    }
   
    public int getLogicalref() {
        return this.logicalref;
    }
    
    public void setLogicalref(int logicalref) {
        this.logicalref = logicalref;
    }
    public String getTask() {
        return this.task;
    }
    
    public void setTask(String task) {
        this.task = task;
    }
    public Date getBegdate() {
        return this.begdate;
    }
    
    public void setBegdate(Date begdate) {
        this.begdate = begdate;
    }
    public Date getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }
    public Date getDateline() {
        return this.dateline;
    }
    
    public void setDateline(Date dateline) {
        this.dateline = dateline;
    }
    public Date getCreatedate() {
        return this.createdate;
    }
    
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    public Integer getUserref() {
        return userref;
    }

    public void setUserref(Integer userref) {
        this.userref = userref;
    }
     
    public Date getModifieddate() {
        return this.modifieddate;
    }
    
    public void setModifieddate(Date modifieddate) {
        this.modifieddate = modifieddate;
    }

    public int getState() {
        return state;
    }

    public void setState(int state) {
        this.state = state;
    }

    public int getInjecttaskref() {
        return injecttaskref;
    }

    public void setInjecttaskref(int injecttaskref) {
        this.injecttaskref = injecttaskref;
    }

    



}


