package com.project.huaweiproject;
// Generated 07.Mar.2019 19:37:43 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

    private int logicalref;
    private String username;
    private String usercode;
    private Integer state;
    private Date createdate;
    private int type;

    public Users() {
    }

    public Users(int logicalref, Date createdate) {
        this.logicalref = logicalref;
        this.createdate = createdate;
    }

    public Users(int logicalref, String username,String usercode, Integer state, Date createdate, int type) {
        this.logicalref = logicalref;
        this.username = username;
        this.usercode = usercode;
        this.state = state;
        this.createdate = createdate;
        this.type = type;
    }

    public int getLogicalref() {
        return logicalref;
    }

    public void setLogicalref(int logicalref) {
        this.logicalref = logicalref;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) { 
        this.username = username;
    }

    public String getUsercode() {
        return usercode;
    }

    public void setUsercode(String usercode) {
        this.usercode = usercode;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public Date getCreatedate() {
        return createdate;
    }

    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

     
    

}
